---
title: Sleep Health and Lifestyle
author: by StowarzyszenieOvi
output: github_document
---

## Summary

W dzisiejszym zabieganym świecie, w którym tempo życia nieustannie przyspiesza, zadbanie o zdrowie psychiczne i fizyczne staje się niezmiernie istotne. Jednym z kluczowych elementów utrzymania równowagi zdrowotnej jest jakość snu. Wartościowy sen wpływa nie tylko na naszą wydajność i energię w ciągu dnia. Przez zrozumienie relacji między snem a codziennymi nawykami możemy lepiej zharmonizować nasze życie, przyczyniając się do długotrwałego dobrostanu zarówno psychicznego, jak i fizycznego. 

Skoro przeciętny człowiek w ciągu swojego całego życia spędza w pracy 36,2 lat, to zadaliśmy sobie pytanie czy rodzaj wykonywanego zawodu ma istotny wpływ na nasz sen? Czy wsytępują różnice w grupach zawodowych pod względem jakości snu  i czy można zidentyfikować konkretne profesje, w których trudności ze snem wydają się bardziej związane z poziomem doświadczanego stresu? Czy są profesje, które są bardziej narażone na zaburzenia snu?

W celu znalezienia odpowiedzi na te pytania wykorzystaliśmy język R oraz narzędzia dostępne w Rmarkdown, aby przeprowadzić analizę danych dotyczącą relacji między zmiennymi. W pierwszym etapie analizy skoncentrowaliśmy się na znalezieniu korelacji między różnymi zmiennymi, co pozwoliło nam lepiej zrozumieć ewentualne powiązania między snem a innymi czynnikami. Następnie wykorzystaliśmy wykresy słupkowe oraz punktowe do wizualnego przedstawienia rozkładu danych, co umożliwiło bardziej czytelne zobrazowanie różnic, np. między grupami zawodowymi.

Okazało się, że lekarze, pielęgniarki i przedstawiciele handlowi doświadczali najwyższych poziomów stresu. Inżynierowie mieli najdłuższy sen, podczas gdy nauczyciele i przedstawiciele handlowi spali najkrócej. W takim razie analiza sugeruje, że istnieje związek między rodzajem zawodu a poziomem stresu pracowników, a co za tym idzie - rodzaj zawodu ma istotny wpływ na długość i jakość snu. 


```{r load-data, echo = FALSE}
# load data here, if you like

url <- "https://raw.githubusercontent.com/IS-UMK/mp-2023-ds-project-StowarzyszenieOvi/master/data/Sleep_dataset.csv?token=GHSAT0AAAAAACNMDJWC6XF3RAOH55D7QKXIZNVQ6OQ"

# Read the dataset from the URL
Sleep_dataset <- read.csv(url)
summary(Sleep_dataset)

```

## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data 

Author:LAKSIKA THARMALINGAM
Date of publication: 2023
Title of dataset: Sleep Health and Lifestyle Dataset
Version: Version 2 (24.14 kB)
Publisher: https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset
Persistent locator/identifier (e.g., DOI): -
Date accessed: 28.01.2024 r.



## References

Strona, z której wzieliśmy naszą bazę danych: https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset
Zdjęcie z 2 oraz 17 slajdu : https://sozaino.site/wp-content/uploads/2023/07/guradesora16.png?fbclid=IwAR1QT6qaMG0q8ZEb58hSTHr18KEJGSuZbGdMJt1Wj_qI8II8UMxAZ3q2hnE
